### PR TITLE
Workbench get servo info

### PR DESCRIPTION
**Pull request by KurtE**
This is the same Pull request to allow the Dynamixel Workbench to allow people on all platforms to get the full list of item names.

This is the same as the OpenCR PR: https://github.com/ROBOTIS-GIT/OpenCR/pull/139

However in this version I added the stuff to split out the strings, and make them unique so that strings like:
"ID", "Model_Number", ...  are not duplicated,  Also found about 3 errors in the servo item definitions where there was a space instead of a _ in the middle of the name.

Also rearranged the items in the ControlTableItem, such that all of the fields align on their natural alignment so no padded needed.  Saved lots of memory that way. 
 
Warning: I have not updated the header files in the released folder yet, nor the library file.  Not sure how much good the lib_f103.a file would be as if any other PR is put in first it makes the one no longer valid.

### CODE REVIEW

**Comment by routiful** [comment]
Hello @KurtE

I'm improssive your contribution. Because the example is depend on OpenCM, I can review your PR.
But revise toolboxis main code of Dynamixel-Workbench.
I think you can PR that in the main reposityro of Dynamisel-Workbench.

Sorry to bothering you.

**Comment by KurtE** [comment]
Hi @routiful and @OpusK,

I may be having an English translation problem.  What are you suggesting?  To not do these level changes?  

Or are you suggesting, that they need to be done first on the main workbench project and then maybe the changes get propagated back to OpenCM and OpenCR?  

But then wondering about the current differences between all of them.  Example OpenCM has different directory names than the others.  Also so methods were added to CM/CR that are maybe not in Workbench... 

Again let me know how you wish to proceed (if at all).

Thanks
Kurt

**Comment by routiful** [comment]
Sorry for my poor English.

Our team policy is that first development about Dynamixel-workbench is proceeded in main repository and second propagate it into OpenCM and OpenCR. And the related example is commited in each repository.

So I think that your PR is more proper to [main repository](https://github.com/ROBOTIS-GIT/dynamixel-workbench)

**Comment by KurtE** [comment]
English... Not a problem.  I was just not fully understanding what it was you wanted/needed.  

So I will try moving the changes over to your main repository and make sure everything builds...
Which I have done, with this Fork/Branch: https://github.com/KurtE/dynamixel-workbench/tree/Allow_OpenCM_OpenCR-Use_full_item_list

What I don't understand is how to properly test the changes on Linux.  Preferably without using ROS (other than using catkin_make and the like to build.  

First: what hardware to use to test it.  I don't have any of your U2D2 or earlier USB2Dynamixel.  I do have a couple of the 3rd party USB2AX.  And of course a couple of OpenCR boards and a few OpemCM boards... Will probably setup an OpenCM board with default firmware, and configured to talk to a couple of servos (right buss and baud rate)...

Second half of question is what programs to run (or modify) to test? 
Put another way are there similar examples to using the dynamixel_workbench_toolbox in the main project.  Example something like:  s_Monitor.ino on the Arduino side?

**Comment by routiful** [comment]
To @KurtE 

You can use OpenCR uploading `usb_to_dxl` example as U2D2.

Also I make simple cmakelist to run dynamixel-workbench in linux without ROS and merge it develop branch.

https://github.com/ROBOTIS-GIT/dynamixel-workbench/tree/develop/dynamixel_workbench_toolbox

It might be help you when you want to test it.

**Pull request merged**
