### PR TITLE
None block UART Writes - More minimal similar to later version for Op…

### PR DESCRIPTION
**Pull request by KurtE**
This is an alternate Pull Request to the earlier version: #38 

The changes in this version are based more on the minimal change version I did up on OpenCR
https://github.com/ROBOTIS-GIT/OpenCR/pull/135

Note: This also contains a version of changes for Serial.getBaudRate which is done the same way as was done on OpenCR.  That is I updated the variable that was used... 

Currently setup that all RX is always DMA and TX can be either IT or DMA, currently all defined as DMA.

I Did not put in any of the DMA Stream arbitration stuff I added to OpenCR as these appear to be the only things using the DMA Streams.  Can add if we wish to enable SPI.

So far I have done some simple testing.  Output only to Serial2, Input from Serial2 and the Pingpong test of Serial->Serial3->Serial2->Serial3->Serial which is working at 1mbs... like writes

I also included some other edits from OpenCR, that helped over there for warning messages.  Things like cont string to Printf.   Also some unused...

I have also done some basic DXL testing.  I ran my Hexapod code base with it using XBee on Serial2 and Servos on Serial3.  I ran the simple Servo forwarder app and it found servos. 

Let me know what you think.

Kurt

### CODE REVIEW

**Comment by KurtE** [comment]
Thought I would show the outputs from the Serial ping pong program, I mentioned above. 

Again more or less same as OpenCR except one less node...
```
uint32_t test_baud = 1000000;
uint8_t buffer[1024]; // Serial buffer..
uint16_t cb;
uint16_t cbAvail;

void setup() {

  // put your setup code here, to run once:
  while (!Serial && millis() < 5000) ;
  Serial.begin(115200);
  Serial3.begin(test_baud);
  Serial2.begin(test_baud);
  Serial.println("Serial ping pong test");
  pinMode(2, OUTPUT);
  digitalWriteFast(2, LOW);
  pinMode(3, OUTPUT);
  digitalWriteFast(3, LOW);
}
void loop() {
  if (!Serial.available()) return; // don't have new line yet
  cb = 0;
  while (Serial.available()) {
    int ch = Serial.read();
    if (ch >= ' ') buffer[cb++] = ch;
  }
  buffer[cb] = 0; // null terminate
  Serial.printf("Line in: %s\n", buffer);
  Serial.print( "Echoed : ");

  uint16_t cbBack = 0; // how many bytes have made it through
  uint32_t start_time = micros();
  uint16_t cnt2 = 0;
  digitalWriteFast(2, HIGH);
  digitalWriteFast(3, HIGH);
  Serial3.write(buffer, cb); 
  digitalWriteFast(3, LOW);
  while ((cbBack < cb) && ((micros()-start_time) < 1000000)) {
    if (cbAvail = Serial2.available()) {
      digitalWriteFast(3, HIGH);
      Serial2.readBytes(buffer, cbAvail);
      Serial2.write(buffer, cbAvail);
      digitalWriteFast(3, LOW);
      cnt2 += cbAvail;
    }

    if (cbAvail = Serial3.available()) {
      digitalWriteFast(3, HIGH);
      Serial3.readBytes(buffer, cbAvail);
      Serial.write(buffer, cbAvail);
      cbBack += cbAvail; // it made it through 
      digitalWriteFast(3, LOW);
    }
  }
  digitalWriteFast(2, LOW);
  uint32_t delta_time = micros() - start_time;
  Serial.printf("\nDelta Time %dus, Cnts: %d %d %d time per char: %d psudo baud %d\n", delta_time, cb, cnt2, cbBack,  delta_time/cb, 
      10000000/(delta_time / cb));
}
```

```
Serial ping pong test
Line in: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
Echoed : abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
Delta Time 832us, Cnts: 62 62 62 time per char: 13 psudo baud 769230
```
And you can see pretty good overlap:
screenshot

As compared to released code...
```
Serial ping pong test
Line in: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
Echoed : abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
Delta Time 2029us, Cnts: 62 62 62 time per char: 32 psudo baud 312500
```
screenshot2

**Comment by KurtE** [comment]
Hi @OpusK,

I made the changes to remove the HAL return function.  Will do the same to OpenCR project. 

This involved also taking care of the Merge of the other code as they conflicted on how things were done. 
That is the Serial.write(buf, cnt) now does the non-blocking code versus new call to HAL that simply wrote the buffer... 

I updated header files to match in released and update lib_f103.a file... 
Warning, I accidentally added a blank lib_f103.a file in the main (non-released) variant folder.  I normally have to either make or copy one  in here to build the dev branch. 

@kijongGil and @OpusK - Dynamixel SDK changes - some of these were to make the file more consistent between OpenCM and OpenCR projects. 

If the goal is to migrate all of the changes into the Dynamixel SDK:  https://github.com/ROBOTIS-GIT/DynamixelSDK

There are two changes between the OpenCM and OpenCR code basis and the SDK.  

The most important one is understanding that with these changes when you do 
SerialX->write(...) the write is not necessarily completed by the time the API completes. 
So code was added to do a SerialX->flush(), which with current released code and with these changes would make sure that the write complete, before we change the direction pin output. 

With current released IDES, Serialx->flush() is a NOP, as the writes complete as part of the API. 
With the code in this PR - the flush would wait until the last byte was output (Transfer complete)

One minor concern is with older releases of the IDE.  I believe there were some early versions of the Arduino release that SerialX->flush() used the Arduino 1.0.x semantics of clear out the input queue versus the current Arduino semantic of wait until data output has completed.  This change started with Arduino 1.5...    

Obviously simplest approach here is to tell people to update to current releases... 

Second issue, is when some of the changes went in to properly fix flush to do the right thing, we added a call to flushRx, which was added at that time: 
https://github.com/ROBOTIS-GIT/OpenCM9.04/blame/master/arduino/opencm_arduino/opencm9.04/libraries/DynamixelSDK/src/dynamixel_sdk/port_handler_arduino.cpp#L112

One fix would again be to say update to current stuff.  The other option is to change the clearPort,  from: 
```
void PortHandlerArduino::clearPort()
{
#if defined(__OPENCR__)
  DYNAMIXEL_SERIAL.flush();
#elif defined(__OPENCM904__)
  p_dxl_serial->flush();
  p_dxl_serial->flushRx(0);
#endif
}
```
to maybe to something like:
```
void PortHandlerArduino::clearPort()
{
  int temp __attribute__((unused));
#if defined(__OPENCR__)
  while (DYNAMIXEL_SERIAL.available()) 
  {
      temp = DYNAMIXEL_SERIAL.read();
  }
#elif defined(__OPENCM904__)
  while (p_dxl_serial->available()) 
  {
      temp =p_dxl_serial->read();
  }
#endif
}
```
Warning typed on fly, so could have issues... 

Let me know what you think.

Kurt

**Comment by KurtE** [comment]
> @KurtE,
> However, the UNUSED macro may not exist in other platform code. I would like to change it to the following form. (void) (parameter);
> 
@OpusK @kijongGil 
With the changes to the file dynamixel_sdk/protocol1_packet_handler.cpp which added the UNUSED macro. 
The changes were only done to help get rid of warning messages, and to make the source files the same between OpenCM and OpenCR.  I still see one difference between the two in packet_handler.h were The OpenCR version has:
```
#define ERROR_PRINT  SerialBT2.print
#else
#define ERROR_PRINT  printf
#endif
```
  
Obviously we have a few options:

a) I could undo the change in the OpenCM one... 

b) Could change all of the occurrences in this file to (void)(pararameter) as you mentioned. 

c) Or could add something like:
```
#ifndef UNUSED
#define UNUSED(x) ((void)(x))
#endif
```
Somewhere at the start of the file. 

Let me know if you would like me to make any of these changes. 

Kurt

P.S. - As for the differences between these two github projects and the Dynamixel SDK project, there are several more differences... Like all of the copyright notices... But more importantly all of the readRx functions have different parameters... readRx, read1ByteRx, Read2ByteRx... 
Example:  from OpenCM/OpenCR
```
 virtual int read1ByteRx     (PortHandler *port, uint8_t *data, uint8_t *error = 0) = 0;
```
Versus Dynamixel SDK
```
 virtual int read1ByteRx     (PortHandler *port, uint8_t id, uint8_t *data, uint8_t *error = 0) = 0;
```
That is the OpenCM/CR versions is missing the id...

**Comment by OpusK** [comment]
@KurtE ,

>Warning typed on fly, so could have issues...

Personally, I totally agree with this.

> a) I could undo the change in the OpenCM one...
> b) Could change all of the occurrences in this file to (void)(pararameter) as you mentioned.
> c) Or could add something like:

I think b, c seems to be good.
c is applicable to the SDK as a whole, so @kijongGil's opinion is necessary.

> P.S. - As for the differences between these two github projects and the Dynamixel SDK project, there are several more differences... Like all of the copyright notices... But more importantly all of the readRx functions have different parameters... readRx, read1ByteRx, Read2ByteRx...
Example: from OpenCM/OpenCR

In this regard, since the SDK is not compatible with the current SDK, it is necessary to update the OpenCR and OpenCM9.04 SDK (in contrast, the changes made in OpenCR and OpenCM9.04 are applied to SDK).

Now that @kijongGil is on a business trip, we'd better wait for him to come back and answer.

**Comment by KurtE** [comment]
@OpusK,

Sounds good, 
Note: with the changes to protocol1_packet_handler - we could just undo it... I simply applied the changes to the OpenCM project that were already in OpenCR project...  I don't think there were any functional changes to that file. 

But we do need the flush calls as to make sure the whole output is completed before changing the state of the IO pin. 

As for merging stuff into the main Dynamixel SDK project.  I was going to suggest that maybe you could do it by checking versions...  But not sure how doable that is with your current setup. 

Or at least by command line, I don't see anything obvious... That is when I do an Arduino build on different platforms, the generated compiler commands, that include the defines:

OpenCR
```
-DBOARD_OpenCR -mcpu=cortex-m7 -DF_CPU=216000000L -DARDUINO=10807 -DARDUINO_OpenCR -DARDUINO_ARCH_OPENCR -mthumb -DSTM32F746xx -D__OPENCR__ 
```
OpenCM
```
-DARM_MATH_CM3 -DUSE_HAL_DRIVER -DBOARD_OpenCM904 -mcpu=cortex-m3 -DF_CPU=72000000L -DARDUINO=10807 -DARDUINO_OpenCM904 -DARDUINO_ARCH_OPENCM9.04 -mthumb -DSTM32F103xB -D__OPENCM904__ "
```
But if you try to compile for a Teensy 3.6 you see something like:
```
 -D__MK66FX1M0__ -DTEENSYDUINO=144 -DARDUINO=10807 -DF_CPU=180000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH 
```
What is interesting here is, with each release of Teensyduino, the version number is updated to match the release.  In this case 1.44.  So for example with a Teensy build, when a new release comes out with new functionality, and we have libraries that need to work with older releases, but would like to make use of the stuff in newer releases... The libraries might do something like:
```
#if TEENSYDUINO < 144
// Do the old way
#else
// do the new stuff
#endif
```
But not sure if there is a way to do it with your current setup...  Like you have some version number as part of some global header. 

Alternative:  With some new functionality features, example in SPI, when implementations added the ability to do transactions, they updated their header file to define: SPI_HAS_TRANSACTION 1
Which then libraries or user programs can detect like above and work with or without them.

So another alternative is we could add to this new stuff for OpenCM and OpenCR we could add a define in one of the header files, like UARTClass.h 

Something like:
```
#define SERIAL_WRITES_NON_BLOCKING 1
```
Then we could change the Dynamixel SDK code to check for this define and only add the flush call if it is defined... So for older versions of the OpenCM/CR Arduino installs, should work like before. 

I would still recommend reworking the old flush the input code to what suggested above.

Hope this makes sense?

**Comment by OpusK** [comment]
@KurtE,

The compilation option looks good. I will discuss this with others, including this one.

In my opinion, we need to apply the SDK's latest API to OpenCR.
I think it's a good idea to use the compile option as you suggested, if necessary.
(Like... -DDXLSDK=3.5.X )

And as you know, changes to the SDK API also affect the Workbench API. We will have to do this.

**Comment by OpusK** [comment]
@KurtE,

As @kijongGil [mentioned](https://github.com/ROBOTIS-GIT/DynamixelSDK/issues/249#issuecomment-430467758), changing the DXL SDK seems to be done separately in OpenCR or OpenCM. (Of course, I think he will continue to review.)

And, as you suggested, I think it would be fine to manage the version of the SDK as a compile option.

**Comment by KurtE** [comment]
@OpusK, @kijongGil -

Wondering about state of this one.  I am assuming from the conflict that the issue is mainly due to PR's after this point, probably the lib_f103.a file

**Comment by KurtE** [comment]
@OpusK and @kijongGil 

I updated the lib_f103.a plus one other header file in the release that was not updated...  

I have not yet updated the Dynamixel SDK files, to match the OpenCR version.   Can do in a few days, but the main differences are the copyright data in the files changed...

**Comment by OpusK** [comment]
@KurtE,

There is still a lib_f103.a file crashing.
Or will we force it to merge later after modifying the SDK and Workbench?

**Comment by KurtE** [comment]
Hi @OpusK,

Not sure what you meant by:

> There is still a lib_f103.a file crashing.

If you meant that it still shows up as conflicting, not sure how to resolve.  I did put up a new one, but it did not mark the conflict as resolved as only someone with write access can?   If you mean that things built are not working?   We may have some more work to do.

Note: I was gone for a few days.  Before that I tried copying in the SDK stuff from OpenCR and was having some issues with some servo messages not working...   So I backed those out.  I think I/We probably need to retry the OpenCR code with the new SDK stuff as well as maybe some of the receive stuff where you now pass in ID, may not been fully updated?  Or maybe it was because one of my servos got corrupted.    This was to the new Burger, after I was trying to setup the servos to work the ROS2 code.    Will probably put in new Issue on Turtlebot project. 

Will try to get some more testing done.  Before I start playing with XEL :D

**Comment by OpusK** [comment]
Hi, @KurtE ,

>> If you meant that it still shows up as conflicting, not sure how to resolve. I did put up a new one, but it did not mark the conflict as resolved as only someone with write access can? 

My word means this.
To fix this, I need to remove the lib.a file from the remote branch and accept yours.
Do you want to merge into this state and proceed with the new PR?

**Comment by KurtE** [comment]
@OpusK, I think we can do it either way. 

You could simply resolve it at that end.  Again I am not GITHUB expert.  Sometimes it is as easy as telling github that the problem was resolved... 

OR if desired, I could create a different branch based on current develop and issue new PR with this code without the conflict... 

Either way works for me. 

Right now I have the Dynamixel SDK code totally hacked up on my main machine, to try to take care of the memory corruption problem I ran into when trying to merge the current SDK code into here...
More on that in the new issue I issued... 

Let me know which way you want to go. 

Kurt

**Comment by KurtE** [comment]
@OpusK, 

This current branch should be working as is.  I have not migrated (checked in) the later code from OpenCR/Dynamixel SDK changes to this thread.    

So again a fewoptions:
a) Go ahead and pull in this PR and all of the updated Dynamixel SDK stuff be done on different PR.  

b) I can pull in the DynamixelSDK updates as it is in OpenCR code base, and undo one change: 
https://github.com/ROBOTIS-GIT/OpenCR/commit/185e36be58c4b33bd14d63ac163508aec9ce5fe1#diff-d6605c9e37c36434682cb27a7ec0a50aL48
In particular where it removed the #if defined(__opencm904__) 
where it reduced the max size of TX and RX packets.

b+) Maybe also add in my change to stuffing code that removes the need for extra MAX buffer.

c) Wait for my updates for Dynamixel SDK changes to reduce memory.   I think it is working OK, but still would like to get your both your and Gilbert's @kijongGil thoughts on some of the issues.  Like would it be OK to try to remove the need for AddStuffing to not need to realloc the buffer and pass the requirement to have enough room for buffers.  This would also impact Workbench.   Or maybe some hack that can detect the difference between packets that are on the stack (or global memory) versus ones that come from heap?  Not sure of any clean way to do this. 

I am comfortable with any of these options.  a) or b) (maybe b+) might be prudent  

And that way could have separate PR's with same changes for just SDK (and maybe WB) for OpenCM as well as OpenCR and the mainline SDK and Workbench.   Also I understand that maybe some more drastic changes to SDK might take awhile as it sounds like Gilbert is busy with other stuff until next year.

**Comment by OpusK** [comment]
@KurtE,

I think option a) is better.
So will you pull the code for this thread up there with a new PR?

**Comment by KurtE** [comment]
I believe that it is in a) now.  My experiments with the SDK was added to different branch

**Comment by KurtE** [comment]
@OpusK, 

As you may have already noticed, I made new PR #53 which I merged in my changes from this PR into current develop sources.  Hopefully everything is correct.

Updated the lib_f103.a file with merged files.  

I built and tried out one of my servo test programs and so far it appears to work...

**Comment by OpusK** [comment]
@KurtE 

So, will this PR be closed?

**Pull request merged**
