### PR TITLE
Uart write change async

### PR DESCRIPTION
**Pull request by KurtE**
I believe I have the Asynchronous SerialX writes working, so I thought I would do a Pull Request, such that you can take a look and see what you think.

I updated the comments in the commits to hopefully have lots of the details. 
I should mention that while doing this I updated the SerialX read buffers to have 128 bytes instead of 256, such that adding a 128 byte write buffer did not raise memory usage.  

I would suggest that one or more of you take a close look at what I did and see what you think.  Likewise you might want to run additional tests.  Example I did not try out any bluetooth tests.  I did use Serial2, to output debug information, that I used a USB to Serial adapter to show the output in a PuTTy window. 

Probably should test more Dynamixel Workbench programs.  Or let me know which ones you think should be run. 

Let me know what you think.

### CODE REVIEW

**Comment by KurtE** [comment]
@OpusK and others
Thought I would mention, that I have started playing with making similar changes to OpenCR code base.  

I thought maybe it would be beneficial to discuss some of the things I looked at when doing the code for this PR and hopefully soon for OpenCR as for some explanation on why I did what I did... 

I have noticed that looked like someone maybe had started doing some similar stuff awhile ago as there is a struct ring_buffer as part of the UARTClass and there is one defined for both RX and TX (Both 2K each), so currently 16K RAM memory used for Serial1-4... 

Again I don't think any of the write code is used to work with this, only SerialX.flush() actually uses the ring buffer.   From the pieces I see, it was setup to use the function: HAL_UART_Transmit_IT
instead of HAL_UART_Transmit to transfer each character, and have the user interrupt, recall it with the next byte out of the ring_buffer...  You can see some of this in the commented out code in:  UARTClass::TxHandler.

Earlier that was my first approach for this PR, but I for myself did not like this approach as, I believe it forces the system to have to do three interrupts for each character output.  You first call the function HAL_UART_Transmit_IT with your one byte buffer, which sets the variables and then enables the TXE interrupt.  So then interrupt happens (UART_Transmit_IT), pulls the byte to transmit.  It then almost immediately will do another TXE interrupt as the byte was transferred to transmit shift register,  At this point the interrupt will see the transfer count is 0 and it will disable TXE and enable TC interrupt.  Then once the byte finishes being transferred and TC happens.  At that point I believe your TxHandler would be called to start up the process for the next byte...  And there will probably be a gap of time between bytes as you wait until the full transfer complete happens before you setup the next byte.  So the hardware double buffering is defeated.

I did not like that much overhead per byte, especially if you are trying to support 2Mbs or 3Mbs... 

So I try to short circuit as much of this as possible.   So when you call the transfer, it instead checks to see if the queue is empty AND TXE is set and directly outputs the byte to TXE...   If you call again (Or use the buffer version of write), it will again check TXE and try to keep queue full.  If you call with buffer, I go ahead and transfer stuff into the queue, but before I return, I check to see if TXE is set again and go ahead and pump the next byte out, before I enable the TXE interrupt... So hopefully minimize interrupt overhead.  

Note: One thing I know I have not tested much (if at all) with this code is handling when the ring buffer gets full and there is still more output to go.  The code is setup to hopefully enable the interrupts and spin waiting for space to be available to put the remaining bytes into the queue... 

Again hope the above makes sense.  Let me know if there are things you would like changed.

Kurt

**Comment by OpusK** [comment]
I personally think it would be good if the user can selectively use both IT and DMA methods.

And another point is to reduce the overhead as you said.

And OpenCR uses a lot of memory in the buffer, and if possible it would be best if the UART could communicate at high speed with minimal memory usage without overhead.

I would like to test it to see if it can handle the amount of data of about 3Mbps, 4.5Mbps and apply the most suitable method.

**Comment by KurtE** [comment]
I agree that it would be great to support a high speed communications on the UARTS, with as minimal overhead as possible.   Which I hope to do!

 

The approach I have done so far for the CM (I will abbreviate the board names), is very similar to what I did several years ago, for the Arduino 8 bit AVR boards, that made it reasonably possible to support DXL outputs without having to write special code… This was stuff I did to hopefully allow Trossen Robotics to get off their own fork of Arduino (latest one is in the vintage of 1.0.4) and onto supporting mainline Arduino…  Luckily I was able to get Arduino to pick up the changes back in 1.5.3? (plus or minus a release…).

 

But by having the system try to first go direct to hardware before putting in queue and then rely on IT to move to hardware… So on CM board I did this.  With this I tried running the code in the PR at 2mbs and it showed some slight gaps between some bytes with my pseudo firmware app, but at 3mbs it showed more or less no gaps, as the timing and such was that it put the entire packet out using the TXE (DR register)  Did not try any faster.

 

As I mentioned I was thinking of trying DMA approach.  Problem with DMA TX is I believe  it is setup to output some fixed number of bytes.   So that Is why I thought about two buffers, which may work pretty well.  But wonder about a few things.  

 

DMA:  There are a limited number of channels (or streams)?  What is unclear to me on the CR boards is suppose that the system is setup to want to use DMA for both SPI and UARTS.  Suppose I wish to use DMA1 Stream4 for UART4_TX but I also may want to use it for SPI2_TX Note: Not sure if both this UART/SPI are setup on this board… But as an example… Can both be active?  If so both want to implement: DMA1_Stream4_IRQHandler  If both can be active, I would assume you would need a combined handler which somehow detects which channel the interrupt is associated with… 

 

DMA or IT: if you go to higher speeds. Like you mentioned 4.5Mbps the solution may depend.  That is with your current Arduino, all SerialX.write(?)  funnel down to SerialX.write(const uint8_t c),  Which again outputs one byte at a time, and current code goes through to Transfer Compete (TC) before returning… First change I put in was to add the virtual function override:  SerialX. write(const uint8_t *buffer, size_t size);

So if you call with buffer or string, it goes through system as one exchange.  At the higher baud rates and assuming sizeT is not overly large, this is about as efficient as it can be.  It loops through your buffer on TXE keeping the double buffering full, and then waits until TC to return for whole buffer. 

 

So in this case for DXL from USB, may be as good as you can do as long as you remember to write as much as you can as one Arduino Serial call…  However if you are doing a large write, like maybe a large Sync Write, which does not send back data and suppose the output is to 25 servos and 8 bytes per servo (position/speed), then  would make sense to send buffer out with IT or DMA such that the sketch could continue…  What exactly the threshold is where this makes sense?  Good question. 

 

As for allowing the user to chose IT or DMA.   Not sure.  With Arduino the idea is to keep thing simple for end users.  So not sure how to setup so one could choose.    But I know that most users now expect that when they do something like: Serial1.print(“Hello World”);, that the system does not wait for this to complete before continuing…   Where it bit me, was when I setup Serial1 on the CM to do debug outputs, as Serial is being used to receive DXL commands from a host)… 

When I started to debug, I added things like: Serial1.println(“IR called”), and found it completely took over the timing… 

 

Kurt

**Comment by KurtE** [comment]
Hi @OpusK @robotpilot @chcbaram @routiful,

Thought I would update on the OpenCR updates to do like this.  I started merging this code in, but then decided to do a detour and try a more minimal change update to see if that works. 

That is to go along the line of what appeared to be a WIP in the OpenCR code base which has large TX buffer built into UARTClass.   I put the current WIP up in a new fork/branch:
https://github.com/KurtE/OpenCR/tree/Async_Serial_minimal

Currently it is only doing Interrupt, not sure yet how hard to do yet.  I may issue PR over there soon to make it easier for all of you see which approach you might like.  Note: The approach currently here I believe can be more efficient as I try to minimize interrupts.  

But the WIP OpenCR does already speed up some of the DXL Outputs, as it does not try to output one byte at a time which then waits until TC happens before starting next byte.... 

With current release code,  You see a gap between bytes.  On the LA output you will see gap between last bit and next start or the stop looks like a 2 stop depending on if byte... About 2.2us instead of 1us...
screenshot

Current WIP code with ISRs  again at 1Mbps,  You can see these gaps are gone.
screenshot2

Note: Could get this part working even more minimal by simply doing the SerialX.write(buffer, cnt) to call the Transfer as one transfer...

**Comment by OpusK** [comment]
Hi, @KurtE 

Sorry for late reply you.
First of all thank you for your great contribution.
However, the code you have modified is the DYNAMIXEL SDK. Especially, in case of port_handler(like [this](https://github.com/ROBOTIS-GIT/OpenCM9.04/pull/38/files#diff-5e699a369acc20a0d25c73ae8610beabR470)) in double, it is common file, so it may cause problems when it is modified. Since the SDK is currently managed by a different team, it seems that some rules need to be followed.
However, the flush() function you added is a required feature when using DMA functions...
I think what we need to worry about, along with the things I mentioned below.

Among the examples that use Serial.print(), it can be assumed that all data is transmitted when the function is exited. Unfortunately, the examples do not call the flush() function further, which can be problematic. 
And, adding the Flush function to the DMA function is also awkward.
I think we need to worry about this.

**Comment by OpusK** [comment]
@KurtE ,

This PR is duplicated with #42, with the lib file conflict issue.
Can you end this PR and continue at #42?

**Comment by KurtE** [comment]
As mentioned this one has been superseded by #42.

**Pull request closed without merging**
