### PR TITLE
WIP - Serial Configurations (Parity and Stop bits)

### PR DESCRIPTION
**Pull request by KurtE**
Put some pieces in place to allow the user to specify that the want  7 bit data with even or odd parity.  Also allow them to specify 2 stop bits if wanted.

Warning: Still WIP - Currently trying to get half duplex to work.  I have not yet updated the release header file(s) nor updated lib file

### CODE REVIEW

**Comment by OpusK** [comment]
@KurtE, 

Is there anything going on in this regard?

**Comment by KurtE** [comment]
Hi @OpusK,

Sorry, I have not been doing much up here for a bit.  I have been busy with PJRC (Teensy 4 beta), plus recovering from surgery....  

I do plan to get back to this.

Note: I believe this part was completed and working.  It is only a side part to what I was starting off to implement, which is the ability (maybe) to use the Uarts in half duplex.    I personally did not need all of the parity and stop bits stuff, although there were other issues out there about this.  So while I was looking at UART code, put in the enhancement. 

What might be missing is updating the 2nd copy of headers and library file.  I did not do this as to avoid conflicts until you had a chance to look at it and say yep and then either of us could copy the files and put in the prebuilt library.

**Comment by OpusK** [comment]
Hi, @KurtE 

> plus recovering from surgery....

Oh... I wish you well.

> I believe this part was completed and working. 

Okay. I was waiting because you commented "WIP" :)
Once I have the urgent things done, I will take a closer look at your PR code and test it.

Thank you for your contribution :)

**Comment by KurtE** [comment]
Closing out detritus

**Pull request closed without merging**
